version: "3.8"
services:
  unifi-controller:
    container_name: unifi-controller
    image: linuxserver/unifi-controller:arm64v8-latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /srv/unifi/data:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    restart: unless-stopped
